export const DS_DESCRIPTIONS: Record<string, string> = {
  DS01: 'PO Copy Not Received',
  DS02: 'PO Rejected',
  DS03: 'PO Pending Revision',
  DS04: 'PO Acknowledged - Delivery On Time',
  DS05: 'PO Acknowledged - Delivery Delay',
  DS06: 'Delivery On Hold - Pending Import Permit',
  DS07: 'PO Acknowledged - No response',
  DS08: 'Delivery On Hold - Pending LC',
  DS09: 'Delivery On Hold - Pending Advance Payment',
  DS10: 'Delivery On-Hold - Payment Issues',
  DS11: 'Delivery On Hold - Others',
  DS12: 'Delivered & Invoiced',
  DS13: 'Service Ongoing',
  DS14: 'Service Completed',
  DS15: 'Shipped - In Transit',
  DS16: 'Ready for Collection',
  DS17: 'Collected by Freight Forwarder',
  DS18: 'Customs Clearance',
  DS19: 'Products Delivered to Base',
};
